# ベースイメージ
FROM python:3.11-slim

# 作業ディレクトリを設定
WORKDIR /app

COPY requirements.txt /app/

# 依存関係をインストール
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py /app/
COPY env.py /app/
COPY psql.py /app/
COPY ptoken.py /app/
COPY pvalid.py /app/
COPY pexperiment.py /app/
COPY create_admin.py /app/
COPY templates/index.html /app/templates/

# Gunicornでアプリを起動
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "main:app"]
