# ベースイメージ
FROM python:3.11-slim

# 作業ディレクトリを設定
WORKDIR /app

COPY requirements.txt /app/

# 依存関係をインストール
RUN pip install --no-cache-dir -r requirements.txt

COPY sensor_server.py /app/sensor_server.py
COPY env.py /app/
COPY pvalid.py /app/

# Gunicornでアプリを起動
CMD ["gunicorn", "-w", "16", "-b", "0.0.0.0:8001", "--timeout", "180", "--keep-alive", "60", "sensor_server:app"]
