from dotenv import load_dotenv
import os

load_dotenv()

APP_SECRET_KEY = os.getenv("APP_SECRET_KEY")
APP_JWT_SECRET_KEY = os.getenv("APP_JWT_SECRET_KEY")

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_DB = os.getenv("REDIS_DB")

POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")

MONGO_HOST = os.getenv("MONGO_HOST")
MONGO_PORT = int(os.getenv("MONGO_PORT"))
MONGO_USER = os.getenv("MONGO_USER")
MONGO_PASSWORD = os.getenv("MONGO_PASSWORD")

INFLUX_HOST = os.getenv("INFLUX_HOST")
INFLUX_PORT = os.getenv("INFLUX_PORT")
INFLUX_ORG = os.getenv("INFLUX_ORG")
INFLUX_BUCKET = os.getenv("INFLUX_BUCKET")
INFLUX_MEASUREMENT = os.getenv("INFLUX_MEASUREMENT")
INFLUX_TOKEN = os.getenv("INFLUX_TOKEN")

VICTORIA_METRICS_HOST = os.getenv("VICTORIA_METRICS_HOST")
VICTORIA_METRICS_EXPORT_PATH = os.getenv("VICTORIA_METRICS_EXPORT_PATH")
VICTORIA_METRICS_WRITE_PATH = os.getenv("VICTORIA_METRICS_WRITE_PATH")
VICTORIA_METRICS_BASE_METRIC_NAME = os.getenv("VICTORIA_METRICS_BASE_METRIC_NAME")